name: cfg_lib
description: A Dart library for working with the CFG configuration format.
version: 0.1.2
homepage: https://docs.red-dove.com/cfg/index.html
repository: https://github.com/vsajip/dart-cfg-lib

environment:
  sdk: '>=2.13.1 <3.0.0'


dependencies:
  path: ^1.8.0
  complex: ^0.7.2
  # timezone: ^0.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
