
name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:  # at 03:06 on day-of-month 12
    - cron: '6 3 12 * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable', 'dev']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{matrix.sdk}}
    - name: Run tests on Windows after setting the HOME environment variable
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $env:HOME = $env:USERPROFILE
        echo "Env: HOME = $env:HOME"
        dart pub get
        dart test
    - name: Run tests on POSIX
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        dart pub get
        dart test --verbose-trace
